import type { ContentBlock } from '../components/content/RichContent';

export const aboutContent: ContentBlock[] = [
  { type: 'heading', level: 2, text: 'The Story Behind the Name' },
  { type: 'paragraph', text: 'Attikid is the creative identity of Travis—a songwriter, storyteller, and artist turning real experiences, memories, mistakes, pain, love, loss, and everything in between into music for people who have ever felt like nobody could possibly understand what they were carrying.' },
  { type: 'paragraph', text: 'Attikid was not created from a marketing strategy or invented character. It grew naturally from a life filled with experiences that were often difficult to explain in ordinary conversation. The identity exists because some emotions are too complicated to summarize, some memories refuse to stay buried, and some things are easier to say through a song than they are to say out loud.' },
  { type: 'paragraph', text: 'Since beginning to write in 2012, Travis has used songwriting as a way to document what life feels like from the inside.' },
  { type: 'paragraph', text: 'Every story begins somewhere real.' },
  { type: 'list', items: ['A memory.', 'A conversation.', 'A relationship.', 'A mistake.', 'A loss.', 'A moment of anger.', 'A moment of weakness.', 'A night that never gets forgotten.', 'A feeling that could not be explained at the time.'] },
  { type: 'paragraph', text: 'Those experiences become the raw material. Attikid takes those pieces and turns them into something tangible.' },
  { type: 'heading', level: 2, text: 'Music Built From Lived Experience' },
  { type: 'paragraph', text: 'The foundation of Attikid is simple: **nothing is written without meaning.**' },
  { type: 'paragraph', text: 'The music draws from lived experiences rather than manufactured narratives. Even when a song becomes fictionalized, exaggerated, metaphorical, or emotionally heightened, its foundation begins with something that was felt, witnessed, remembered, feared, desired, or survived.' },
  { type: 'paragraph', text: 'That authenticity gives the music its purpose.' },
  { type: 'paragraph', text: 'Through alternative rap, emo-rap, melodic rap, introspective songwriting, atmospheric production, and emotionally driven confessionals, Attikid explores the parts of life that people often hide from everyone else.' },
  { type: 'list', items: ['Love and heartbreak.', 'Attachment and abandonment.', 'Addiction and temptation.', 'Regret and redemption.', 'Loneliness and connection.', 'Anger and vulnerability.', 'Confidence and insecurity.', 'Growing up.', 'Losing people.', 'Becoming someone different.', 'Trying to understand who you were before life changed you.'] },
  { type: 'paragraph', text: 'The music does not attempt to pretend that everything has a clean ending.' },
  { type: 'paragraph', text: 'Sometimes there is no lesson. Sometimes there is no closure. Sometimes the only honest conclusion is that something hurt, it changed you, and you are still learning how to live with what happened.' },
  { type: 'paragraph', text: 'That honesty is intentional. Attikid is not interested in pretending to have all the answers. The music is about asking the questions.' },
  { type: 'heading', level: 2, text: 'I Understand.' },
  { type: 'paragraph', text: 'At the center of Attikid is a message that can be reduced to four words: **You are not alone.**' },
  { type: 'paragraph', text: 'Not necessarily because the listener experienced the exact same thing. Not because two lives are identical. But because pain has patterns. Grief has patterns. Loneliness has patterns. Fear has patterns. Love has patterns. Regret has patterns.' },
  { type: 'paragraph', text: 'There is something powerful about hearing another person describe a feeling you thought existed only inside your own head. That is where Attikid lives.' },
  { type: 'list', items: ['The person sitting alone in their room.', 'The person driving with the windows down because they do not know what else to do.', 'The person replaying an old conversation.', 'The person trying not to text someone.', 'The person who misses somebody they know they should not miss.', 'The person pretending everything is fine.', 'The person rebuilding themselves quietly.', 'The person who has survived things they rarely talk about.', 'The person who does not need someone to tell them how to feel—they simply need proof that they are not the only person who feels that way.'] },
  { type: 'paragraph', text: 'Attikid is that proof.' },
  { type: 'heading', level: 2, text: 'Why Attikid?' },
  { type: 'paragraph', text: 'The name is built around the idea of an **attic**. An attic is where things are stored: old photographs, childhood possessions, letters, clothes, and objects nobody uses anymore but nobody can bring themselves to throw away.' },
  { type: 'paragraph', text: 'Some memories are valuable. Some are painful. Some are embarrassing. Some are beautiful. Some are things we forgot existed until we opened an old box and suddenly remembered exactly who we were.' },
  { type: 'paragraph', text: 'That makes the attic a powerful metaphor for the human mind. We store things away, put memories into boxes, bury conversations, suppress feelings, hide wounds, and move forward because life requires us to keep moving.' },
  { type: 'paragraph', text: 'But moving forward does not always mean something has been resolved. Sometimes it simply means we learned how to carry it.' },
  { type: 'paragraph', text: 'Attikid represents the person willing to go back into that room: to open the boxes, confront what was left behind, examine the memories, revisit the moments, acknowledge the wounds, and bring those things into the light.' },
  { type: 'paragraph', text: 'The attic is not simply a symbol of darkness. It is a place of discovery where forgotten pieces of ourselves can be found again. That is what the music attempts to do.' },
  { type: 'heading', level: 2, text: 'Music as Documentation' },
  { type: 'paragraph', text: 'Attikid is not only about entertainment. It is also documentation. Songs become snapshots of specific emotional periods.' },
  { type: 'paragraph', text: 'A record can preserve the feeling of being seventeen. Another can preserve the feeling of losing someone. Another can capture the chaos of a relationship. Another can represent a specific version of Travis that no longer exists.' },
  { type: 'paragraph', text: 'Years later, the circumstances may change, but the song remains. That makes music a kind of emotional archive.' },
  { type: 'paragraph', text: 'Every song adds another piece to the larger story. Some pieces may be dark, romantic, angry, hopeful, uncomfortable, or contradictory. That is part of the point. People are not one emotion; people are collections of experiences.' },
  { type: 'heading', level: 2, text: 'There Is No Perfect Version of the Story' },
  { type: 'paragraph', text: 'Attikid does not exist to construct a flawless public persona. The objective is not perfection. It is honesty.' },
  { type: 'list', items: ['You can love someone and still be hurt by them.', 'You can forgive someone and still remember what they did.', 'You can miss someone and know they should not come back.', 'You can be proud of yourself and still struggle with who you are becoming.', 'You can survive something and still be affected by it years later.'] },
  { type: 'paragraph', text: 'Healing does not erase history. Growing does not require pretending the past never happened. And strength does not always look like confidence. Sometimes strength is simply getting up and continuing.' },
  { type: 'heading', level: 2, text: 'A Creative World, Not Just an Artist Name' },
  { type: 'paragraph', text: 'Although music is the foundation, Attikid is intended to become something larger: a creative universe built around **honesty, memory, resilience, identity, and expression.**' },
  { type: 'paragraph', text: 'Music is one layer. Writing is another. Visual art, fashion, stories, concepts, collaborations, films, digital experiences, and future creative projects can expand the world even further.' },
  { type: 'paragraph', text: 'K!D SUPPLY is part of that evolution. Rather than functioning as a disconnected merchandise brand, it can exist as a physical extension of the Attikid philosophy—a place where the ideas, symbols, language, and aesthetic surrounding the project become tangible.' },
  { type: 'paragraph', text: 'The objective is to create a world people can enter, not simply a catalog they can consume. Different mediums. Same core philosophy.' },
  { type: 'heading', level: 2, text: 'For the People Who Survived Quietly' },
  { type: 'list', items: ['The person who survived quietly.', 'The person whose hardest battles were invisible.', 'The person who learned how to smile while carrying something heavy.', 'The person who never found the right words.', 'The person who had to grow up faster than they were supposed to.', 'The person who lost pieces of themselves along the way.', 'The person who is still healing.', 'The person who refuses to stop moving toward the future.'] },
  { type: 'paragraph', text: 'Attikid does not promise that everything will be okay. Instead, it offers something more honest: **You are still here.**' },
  { type: 'paragraph', text: 'Your memories matter. Your experiences matter. Your scars matter. Your mistakes matter. Your voice matters. And your story has value—even when the story is unfinished.' },
  { type: 'heading', level: 2, text: 'The Future of Attikid' },
  { type: 'paragraph', text: 'Attikid is still being built. The catalog will continue to grow. The stories, sound, visuals, and creative world will evolve.' },
  { type: 'paragraph', text: 'Some chapters will be darker than others. Some will be more vulnerable. Some will be louder. Some will be quieter. But the foundation will remain the same: real experiences, real emotion, real stories, no requirement to pretend, and no requirement to have everything figured out.' },
  { type: 'paragraph', text: 'Because somewhere between the things we remember, the things we regret, the things we lost, and the things we survived, there is a story worth telling. Attikid exists to tell it.' },
  { type: 'quote', text: 'I understand. You are not the only one. You made it this far. Your story is not over.' },
];
